Ser Kaelen:Sir Kaelen
Phandelin:Fandelini,Finland,Phandolin,Phandaline,Vandalin,Vandelin,Fandelin,Fandland
House Margaster:Housma Gaster
Brewbarry:Brubberry,blueberry,brewery,Brewery,Burberry,Blueberry,Brewberry,brewberry
Vukradin:Vucrid,Vucra Dinn,Vucherdin,Vukraden,Wukrudin,Viklidin,Vurkidin,Brookertime,Vukerdin,Vukrudin,Vukriddin,Ukradin,Wukradin
VUKRADIN:VUCRUT,VUCRUT IN
Kaelin:Kaelin,Kaelen,Kalen
Valphine:Valphineha,Valtene,Belfina,Valtine,Belfide,Volfina,Velfini,Valphinene,Valphinea,Balfine,Rafina,Valfinay,Alfina,Bellfini,Valfin,Valfini
VALPHINE:BELL FINE
Lathander:Lithantr,Lithander,Left-hander
Lord Nevermber:Lord nevermember,Lord never remembers,Nord nevermembers,'Lord, nevermember'
Zhentarim:Zentarim,Zentarn
Kayla:Caleb
Valphine:Valphinee,Valphineha,Valphinei,Valphinea,Valphineos
Locutus:Lacutus,Locuti
Corbin:Corbyn
Soma:ASOMA
Conyberry:Connie Berry,Connaberry
Borg:Reviaborg
Neverwinter Wood:Neverwinterwood
Gauntlet:Wadawat