# coding: utf-8

"""
    Item Service API

    API for managing items.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from todo_api_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_item(self) -> None:
        """Test case for create_item

        Create a new item
        """
        pass

    def test_delete_item_by_id(self) -> None:
        """Test case for delete_item_by_id

        Delete an item by its ID
        """
        pass

    def test_get_item_by_id(self) -> None:
        """Test case for get_item_by_id

        Get an item by its ID
        """
        pass

    def test_get_items(self) -> None:
        """Test case for get_items

        List all items
        """
        pass

    def test_update_item_by_id(self) -> None:
        """Test case for update_item_by_id

        Update an existing item
        """
        pass


if __name__ == '__main__':
    unittest.main()
