# coding: utf-8

"""
    Item Service API

    API for managing items.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from todo_api_client.models.update_item import UpdateItem

class TestUpdateItem(unittest.TestCase):
    """UpdateItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateItem:
        """Test UpdateItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateItem`
        """
        model = UpdateItem()
        if include_optional:
            return UpdateItem(
                name = '',
                description = '',
                priority = 56
            )
        else:
            return UpdateItem(
                name = '',
                priority = 56,
        )
        """

    def testUpdateItem(self):
        """Test UpdateItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
